### ISSUE TITLE
warning: cast from pointer to integer of different size with gcc 11

### ISSUE THREAD

**Issue by ghost** [JsBergbau/BindToInterface#1]
Hi, I noticed your [comment](https://github.com/netblue30/firejail/issues/3000#issuecomment-855256910) on the Firejail issue tracker and wanted to experiment with BindToInterface. Just wanted to inform you of a warning thrown by gcc on Arch Linux.

$ `gcc -nostartfiles -fpic -shared bindToInterface.c -o bindToInterface.so -ldl -D_GNU_SOURCE`
```
bindToInterface.c: In function ‘connect’:
bindToInterface.c:128:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  128 |         int ret = (int)original_connect(sockfd, addr, addrlen);
      |                   ^
```

$ `gcc --version`
```
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JsBergbau** [comment]
Hi  glitsj16,
thanks for sharing this. Issue occured on 64 Bit only. I've updated the code. Should now compile without warnings.

If you notice anything else, feel free to report.

**Comment by ghost** [comment]
Issue fixed, thanks for your speedy response. Really enjoy using this, much cleaner than my previous set of scripts I had for 'application routing'. And via LD_PRELOAD things quite easily plug into Firejail profiles too. All in all nothing but wins by accidentally finding this gem.

Keep well.
