### ISSUE TITLE
Trying with usenet

### ISSUE THREAD

**Issue by scriptzteam** [JsBergbau/BindToInterface#2]
Hi, 
what could cause this? Its tun0 interface (openvpn) also curl reporting the vpn ip

[WARN] NNTP connection failed: getaddrinfo EAI_AGAIN news.usenet.farm news.usenet.farm:563, reconnecting after 5 second(s)... (attempt 1/100000000000)
[WARN] NNTP connection failed: getaddrinfo EAI_AGAIN news.usenet.farm news.usenet.farm:563, reconnecting after 5 second(s)... (attempt 1/100000000000)
[WARN] NNTP connection failed: getaddrinfo EAI_AGAIN news.usenet.farm news.usenet.farm:563, reconnecting after 5 second(s)... (attempt 1/100000000000)
[WARN] NNTP connection failed: getaddrinfo EAI_AGAIN news.usenet.farm news.usenet.farm:563, reconnecting after 5 second(s)... (attempt 1/100000000000)

**Comment by JsBergbau** [comment]
Could be a DNS issue. Did you also use export `DNS_OVERRIDE_IP=8.8.8.8` or the IP address of your DNS provider?

**Comment by scriptzteam** [comment]
Hmm yes

BIND_INTERFACE=tun0 DNS_OVERRIDE_IP=8.8.8.8 LD_PRELOAD=./bindToInterface.so curl ifconfig.me

reporting the vpn ip

**Comment by JsBergbau** [comment]
Then there could be some block by the vpn provider or the vpn IP by the usenet provider. To verify, use it without LD preload but redirect-gateway option of openvpn, so that all traffic is going through vpn without binding to that interface. When problem didn't occur please also check if curl reports the same IP of the vpn tunnel.

**Comment by scriptzteam** [comment]
Hmm still tryin different commands and seems to work...

curl --interface tun0 canhazip.com
185.163.110.11

BIND_INTERFACE=tun0 DNS_OVERRIDE_IP=8.8.8.8 LD_PRELOAD=/root/BindToInterface/bindToInterface.so curl canhazip.com
185.163.110.11

**Comment by JsBergbau** [comment]
What were your results when using redirect-gateway openvpn option?
Edit: I've tested a lot before publishing the software here. I all cases it worked as expected.

**Comment by JsBergbau** [comment]
To get more information you can recompile, but uncomment line 13 and post the output here

https://github.com/JsBergbau/BindToInterface/blob/main/bindToInterface.c#L13
